/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.*;
import Business.Organization.PharmacistOrganization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keshav
 */
public class AddEditLabTest extends javax.swing.JPanel {

    /**
     * Creates new form AddEditLabTest
     */
    private JPanel userProcessContainer;
    private PharmacistOrganization pharmacistOrganization;
    private Lab lab;
    private Enterprise enterprise;
    private EcoSystem business;

    public AddEditLabTest(JPanel userProcessContainer, PharmacistOrganization organization, Enterprise enterprise, Lab lab, EcoSystem business) {
        initComponents();
        this.pharmacistOrganization = organization;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.lab = lab;
        this.business = business;

        if (lab != null) {
            NameTextField.setText(lab.getLabTestName());
            InstrumentUsedTextField.setText(lab.getInstrument());
            TimeTakenTextField.setText(lab.getTimeTaken());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblInstrumentUsed = new javax.swing.JLabel();
        lblTimeTaken = new javax.swing.JLabel();
        lblAddEditLab = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        TimeTakenTextField = new javax.swing.JTextField();
        InstrumentUsedTextField = new javax.swing.JTextField();

        lblName.setText("Name:");

        lblInstrumentUsed.setText("Instrument Used:");

        lblTimeTaken.setText("Time Taken:");

        lblAddEditLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddEditLab.setText("Add/Edit Lab");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstrumentUsed)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTimeTaken, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(InstrumentUsedTextField)
                            .addComponent(TimeTakenTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblAddEditLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnBack)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAddEditLab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstrumentUsed)
                    .addComponent(InstrumentUsedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeTaken)
                    .addComponent(TimeTakenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(13, 13, 13)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (NameTextField.getText().isEmpty() || InstrumentUsedTextField.getText().isEmpty() || TimeTakenTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            return;
        }

        if (business.getDrugListObject().getDrugList().size() > 0) {
            if (business.getLabListDirectory().searchLabTests(NameTextField.getText()) != null) {
                JOptionPane.showMessageDialog(null, "Lab with the same name already exists");
                return;
            }
        }

        if (lab != null) {
            lab.setLabTestName(NameTextField.getText());
            lab.setInstrument(InstrumentUsedTextField.getText());
            lab.setTimeTaken(TimeTakenTextField.getText());
        } else {
            Lab addNewLab = business.getLabListDirectory().addLab();
            addNewLab.setLabTestName(NameTextField.getText());
            addNewLab.setInstrument(InstrumentUsedTextField.getText());
            addNewLab.setTimeTaken(TimeTakenTextField.getText());
        }

        JOptionPane.showMessageDialog(null, "Lab test saved successfully");
        lab = null;
        clear();

    }//GEN-LAST:event_btnSaveActionPerformed

    public void clear() {
        NameTextField.setText("");
        InstrumentUsedTextField.setText("");
        TimeTakenTextField.setText("");
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabJPanel lst = (LabJPanel) component;
        lst.clear();
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InstrumentUsedTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField TimeTakenTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddEditLab;
    private javax.swing.JLabel lblInstrumentUsed;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTimeTaken;
    // End of variables declaration//GEN-END:variables
}
