/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.*;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keshav
 */
public class AddEditDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEditDrugJPanel
     */
    private JPanel userProcessContainer;
    private PharmacistOrganization pharmacistOrganization;
    private Drug drug;
    private Enterprise enterprise;
    private EcoSystem business;

    public AddEditDrugJPanel(JPanel userProcessContainer, Organization organization, Enterprise enterprise, Drug drug, EcoSystem business) {
        initComponents();
        this.pharmacistOrganization = (PharmacistOrganization)organization;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.drug = drug;
        this.business = business;

        if (drug != null) {
            txtName.setText(drug.getDrugName());
            txtDrugId.setText(String.valueOf(drug.getDrugId()));
            txtStrength.setText(String.valueOf(drug.getStrength()));
            txtStrengthUnit.setText(drug.getStrengthUnit());
            txtVolume.setText(String.valueOf(drug.getVolume()));
            txtVolumeUnit.setText(drug.getVolumeUnit());
            txtDispenseQty.setText(String.valueOf(drug.getDispenseQty()));
            txtDispenseQtyUnit.setText(drug.getDispenseQtyUnit());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtStrength = new javax.swing.JTextField();
        lblAddEditLab = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        lblStrength = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtVolume = new javax.swing.JTextField();
        lblStrengthUnit = new javax.swing.JLabel();
        txtStrengthUnit = new javax.swing.JTextField();
        lblVolumeUnit = new javax.swing.JLabel();
        txtVolumeUnit = new javax.swing.JTextField();
        lblDispenseQty = new javax.swing.JLabel();
        txtDispenseQty = new javax.swing.JTextField();
        lblDispenseQtyUnit = new javax.swing.JLabel();
        txtDispenseQtyUnit = new javax.swing.JTextField();
        lblDrugID = new javax.swing.JLabel();
        txtDrugId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        drugTypejComboBox = new javax.swing.JComboBox<>();

        lblName.setText("Name:");

        lblAddEditLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddEditLab.setText("Add/Edit Product");

        lblVolume.setText("Volume:");

        lblStrength.setText("Strength:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblStrengthUnit.setText("Unit:");

        lblVolumeUnit.setText("Unit:");

        lblDispenseQty.setText("Dispense Qty:");

        lblDispenseQtyUnit.setText("Unit:");

        lblDrugID.setText("Drug Id:");

        jLabel1.setText("Drug Type:");

        drugTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Tablet", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblAddEditLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDrugID)
                                .addGap(18, 18, 18)
                                .addComponent(txtDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName)
                                    .addComponent(lblVolume)
                                    .addComponent(lblDispenseQty)
                                    .addComponent(lblStrength)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtStrength)
                                            .addComponent(txtVolume)
                                            .addComponent(txtDispenseQty, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblStrengthUnit)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtStrengthUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblVolumeUnit)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtVolumeUnit))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDispenseQtyUnit)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDispenseQtyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEditLab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblName))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStrength)
                    .addComponent(txtStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStrengthUnit)
                    .addComponent(txtStrengthUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVolume)
                    .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVolumeUnit)
                    .addComponent(txtVolumeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDispenseQty)
                    .addComponent(txtDispenseQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDispenseQtyUnit)
                    .addComponent(txtDispenseQtyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(drugTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean NameCheck = true;
        if (txtName.getText().isEmpty() || txtStrength.getText().isEmpty() || txtVolume.getText().isEmpty()
                || txtStrengthUnit.getText().isEmpty() || txtVolumeUnit.getText().isEmpty()
                || txtDispenseQty.getText().isEmpty() || txtDispenseQtyUnit.getText().isEmpty() || drugTypejComboBox.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            return;
        }

        if (drug != null) {
            if (txtName.getText().equalsIgnoreCase(drug.getDrugName())) {
                NameCheck = false;
            }
        }

        if (NameCheck) {
            if (business.getDrugListObject().getDrugList().size() > 0) {
                if (business.getDrugListObject().searchDrugTests(txtName.getText()) != null) {
                    JOptionPane.showMessageDialog(null, "Drug with the same name already exists");
                    return;
                }
            }
        }
        
        try {
            if (Float.parseFloat(txtStrength.getText()) <= 0 || Float.parseFloat(txtVolume.getText()) <= 0
                    || Integer.parseInt(txtDispenseQty.getText()) <= 0 || Integer.parseInt(txtDrugId.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Please strength/volume/dispenseqty/drugID greater than 0");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter decimals in strength/volume and dispenseqty/drugID");
            return;
        }

        if (drug != null) {
            drug.setDrugName(txtName.getText());
            drug.setDrugId(Integer.parseInt(txtDrugId.getText()));
            drug.setStrength(Float.parseFloat(txtStrength.getText()));
            drug.setStrengthUnit(txtStrengthUnit.getText());
            drug.setVolume(Float.parseFloat(txtVolume.getText()));
            drug.setVolumeUnit(txtVolumeUnit.getText());
            drug.setDispenseQty(Integer.parseInt(txtDispenseQty.getText()));
            drug.setDispenseQtyUnit(txtDispenseQtyUnit.getText());
            drug.setDrugType(drugTypejComboBox.getSelectedItem().toString());
        } else {
            Drug addNewDrug = business.getDrugListObject().addDrug();
            addNewDrug.setDrugId(Integer.parseInt(txtDrugId.getText()));
            addNewDrug.setDrugName(txtName.getText());
            addNewDrug.setStrength(Float.parseFloat(txtStrength.getText()));
            addNewDrug.setStrengthUnit(txtStrengthUnit.getText());
            addNewDrug.setVolume(Float.parseFloat(txtVolume.getText()));
            addNewDrug.setVolumeUnit(txtVolumeUnit.getText());
            addNewDrug.setDispenseQty(Integer.parseInt(txtDispenseQty.getText()));
            addNewDrug.setDispenseQtyUnit(txtDispenseQtyUnit.getText());
            addNewDrug.setDrugType(drugTypejComboBox.getSelectedItem().toString());
        }

        JOptionPane.showMessageDialog(null, "Drug saved successfully");
        drug = null;
        clear();
    }//GEN-LAST:event_btnSaveActionPerformed

    public void clear() {
        txtName.setText("");
        txtDrugId.setText("");
        txtStrength.setText("");
        txtStrengthUnit.setText("");
        txtVolume.setText("");
        txtVolumeUnit.setText("");
        txtDispenseQty.setText("");
        txtDispenseQtyUnit.setText("");
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProductJPanel pst = (ProductJPanel) component;
        pst.clear();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> drugTypejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddEditLab;
    private javax.swing.JLabel lblDispenseQty;
    private javax.swing.JLabel lblDispenseQtyUnit;
    private javax.swing.JLabel lblDrugID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStrength;
    private javax.swing.JLabel lblStrengthUnit;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JLabel lblVolumeUnit;
    private javax.swing.JTextField txtDispenseQty;
    private javax.swing.JTextField txtDispenseQtyUnit;
    private javax.swing.JTextField txtDrugId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStrength;
    private javax.swing.JTextField txtStrengthUnit;
    private javax.swing.JTextField txtVolume;
    private javax.swing.JTextField txtVolumeUnit;
    // End of variables declaration//GEN-END:variables
}