/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Order.*;
import Business.Order.Lab;
import Business.Organization.DoctorOrganization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keshav
 */
public class AddHighRiskCategoriesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddHighRiskCategoriesJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Drug drug;
    private Lab lab;
    private Enterprise enterprise;

    public AddHighRiskCategoriesJPanel(JPanel userProcessContainer, DoctorOrganization organization, Enterprise enterprise, Drug drug, Lab lab) {
        initComponents();
        this.doctorOrganization = organization;
        this.userProcessContainer = userProcessContainer;
        this.drug = drug;
        this.lab = lab;
        this.enterprise = enterprise;
        txtOrderLab.setEnabled(false);

        if (lab == null) {
            txtOrderLab.setText(drug.getDrugName());
            txtRangeGreater.setEnabled(false);
            txtRangeLesser.setEnabled(false);
        } else {
            txtOrderLab.setText(lab.getLabTestName());
        }
        txtOrderLab.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblAddEditHRC = new javax.swing.JLabel();
        txtRangeGreater = new javax.swing.JTextField();
        lblRangeGreater = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblOrderLab = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtOrderLab = new javax.swing.JTextField();
        lblRangeLesser = new javax.swing.JLabel();
        txtRangeLesser = new javax.swing.JTextField();

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAddEditHRC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddEditHRC.setText("Add High-Risk Categories");

        lblRangeGreater.setText("Range Greater:");

        lblOrderLab.setText("Orderable / Lab: ");

        lblName.setText("High-Risk Category Name:");

        lblRangeLesser.setText("Range Lesser:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblAddEditHRC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRangeLesser)
                            .addComponent(lblName)
                            .addComponent(lblRangeGreater)
                            .addComponent(lblOrderLab))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrderLab)
                            .addComponent(txtName)
                            .addComponent(txtRangeGreater)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRangeLesser))))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAddEditHRC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblName))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderLab)
                    .addComponent(txtOrderLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRangeGreater)
                    .addComponent(txtRangeGreater, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRangeLesser)
                    .addComponent(txtRangeLesser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(17, 17, 17)
                .addComponent(btnBack)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            return;
        }
        if (enterprise.getHighRiskCriteriaDirectory().searchHRC(txtName.getText()) != null) {
            JOptionPane.showMessageDialog(null, "HRC with same name exists");
            return;
        }

        if (drug == null) {
            try {
                if (!txtRangeGreater.getText().isEmpty()) {
                    if (Float.parseFloat(txtRangeGreater.getText()) <= 0) {
                        JOptionPane.showMessageDialog(null, "Please greater range greater than 0");
                        return;
                    }
                }
                if (!txtRangeLesser.getText().isEmpty()) {
                    if (Float.parseFloat(txtRangeLesser.getText()) <= 0) {
                        JOptionPane.showMessageDialog(null, "Please lesser range greater than 0");
                        return;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter range in decimal numbers");
                return;
            }
        }

        HighRiskCriteria newHRC = enterprise.getHighRiskCriteriaDirectory().addHRC();
        newHRC.setHRCName(txtName.getText());
        newHRC.setHRCId((int) (Math.random() * 50 + 1));
        if (drug != null) {
            newHRC.setDrugName(txtOrderLab.getText());
            newHRC.setHRCName(txtName.getText());
            newHRC.setIsLab(false);
            newHRC.setIsGreaterRangeAvailable(false);
            newHRC.setIsLesserRangeAvailable(false);
        } else {
            newHRC.setLabName(txtOrderLab.getText());
            newHRC.setIsLab(true);
            newHRC.setIsGreaterRangeAvailable(false);
            newHRC.setIsLesserRangeAvailable(false);
            if (!txtRangeGreater.getText().isEmpty()) {
                newHRC.setGreaterRange(Float.parseFloat(txtRangeGreater.getText()));
                newHRC.setIsGreaterRangeAvailable(true);
            }
            if (!txtRangeLesser.getText().isEmpty()) {
                newHRC.setLesserRange(Float.parseFloat(txtRangeLesser.getText()));
                newHRC.setIsLesserRangeAvailable(true);
            }

        }
        JOptionPane.showMessageDialog(null, "High Risk Category saved successfully");
        back();
    }//GEN-LAST:event_btnSaveActionPerformed

    public void back() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        userProcessContainer.remove(component);
        componentArray = userProcessContainer.getComponents();
        component = componentArray[componentArray.length - 1];
        HighRiskCriteriaJPanel hrc = (HighRiskCriteriaJPanel) component;
        hrc.clear();
        hrc.populate();
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddEditHRC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderLab;
    private javax.swing.JLabel lblRangeGreater;
    private javax.swing.JLabel lblRangeLesser;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrderLab;
    private javax.swing.JTextField txtRangeGreater;
    private javax.swing.JTextField txtRangeLesser;
    // End of variables declaration//GEN-END:variables
}
