/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Order.*;

/**
 *
 * @author keshav
 */
public class HighRiskCriteriaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HighRiskCriteriaJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    
    public HighRiskCriteriaJPanel(JPanel userProcessContainer, DoctorOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.doctorOrganization = organization;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HighRiskCategoriesJTable = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("High Risk Categories");

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearch.setText("Search HRC:");

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        HighRiskCategoriesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Orderable", "Lab Test", "Condition "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HighRiskCategoriesJTable);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtsearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(enterpriseLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(187, 187, 187)
                                .addComponent(btnDelete)
                                .addGap(42, 42, 42)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSearch)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnAdd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack)))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    public void clear() {
        txtsearch.setText("");
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchtext = txtsearch.getText().trim().toLowerCase();
        if (searchtext.length() > 0) {
            if (enterprise.getHighRiskCriteriaDirectory().getHighRiskCriteriaList().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No high risk categories. Please add high risk category.");
                return;
            }
            populate();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter search text");
            return;
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) HighRiskCategoriesJTable.getModel();
        dtm.setRowCount(0);
        String searchtext = txtsearch.getText().trim().toLowerCase();

        if (searchtext.length() > 0) {
            for (HighRiskCriteria hrc : enterprise.getHighRiskCriteriaDirectory().getHighRiskCriteriaList()) {
                if (hrc.getHRCName().trim().toLowerCase().contains(searchtext)) {
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = hrc.getHRCId();
                    row[1] = hrc;
                    if (!hrc.isIsLab()) {
                        row[2] = hrc.getDrugName();
                    } else {
                        row[2] = "-";
                    }
                    if (hrc.isIsLab()) {
                        row[3] = hrc.getLabName();
                    } else {
                        row[3] = "-";
                    }
                    if (hrc.isIsGreaterRangeAvailable() && hrc.isIsLesserRangeAvailable()) {
                        row[4] = "> " + hrc.getGreaterRange() + "   " + "< " + hrc.getLesserRange();
                    } else if (hrc.isIsGreaterRangeAvailable()) {
                        row[4] = "> " + hrc.getGreaterRange();
                    } else if (hrc.isIsLesserRangeAvailable()) {
                        row[4] = "< " + hrc.getLesserRange();
                    } else {
                        row[4] = "-";
                    }
                    dtm.addRow(row);
                }
            }
        } else {
            for (HighRiskCriteria hrc : enterprise.getHighRiskCriteriaDirectory().getHighRiskCriteriaList()) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = hrc.getHRCId();
                row[1] = hrc;
                if (!hrc.isIsLab()) {
                    row[2] = hrc.getDrugName();
                } else {
                    row[2] = "-";
                }
                if (hrc.isIsLab()) {
                    row[3] = hrc.getLabName();
                } else {
                    row[3] = "-";
                }
                if (hrc.isIsGreaterRangeAvailable() && hrc.isIsLesserRangeAvailable()) {
                    row[4] = "> " + hrc.getGreaterRange() + "   " + "< " + hrc.getLesserRange();
                } else if (hrc.isIsGreaterRangeAvailable()) {
                    row[4] = "> " + hrc.getGreaterRange();
                } else if (hrc.isIsLesserRangeAvailable()) {
                    row[4] = "< " + hrc.getLesserRange();
                } else {
                    row[4] = "-";
                }
                dtm.addRow(row);
            }
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = HighRiskCategoriesJTable.getSelectedRow();
        if (selectedRow >= 0) {
            HighRiskCriteria hrc = (HighRiskCriteria) HighRiskCategoriesJTable.getValueAt(selectedRow, 0);
            enterprise.getHighRiskCriteriaDirectory().deleteHRC(hrc);
            populate();
        } else {
            JOptionPane.showMessageDialog(null, "Please select high risk criteria.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("SelectDrugLab", new SelectDrugLab(userProcessContainer, doctorOrganization, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HighRiskCategoriesJTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
