/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Order.*;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keshav
 */
public class PatientDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientDetailsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Patient patient;
    private DoctorOrganization doctorOrganization;
    private String PhysicianNotes;
    private EcoSystem system;
    DateFormat timeStampTemp = new SimpleDateFormat("yyyy-dd-MM HH:mm:ss");
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public PatientDetailsJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, Enterprise enterprise, Patient patient, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patient = patient;
        this.doctorOrganization = doctorOrganization;
        this.system = system;
        loadpatientinfo();
        populateOrders();
        populateLabOrders();
        PhysicianNotes = patient.getPhysicianNotes();
    }

    private void loadpatientinfo() {
        lblValuePatientName.setText(patient.getPatientName());
        lblValuePatientMRN.setText(String.valueOf(patient.getMRN()));
        lblValueLocation.setText(patient.getPatientLocation());
        lblValueAge.setText(String.valueOf(patient.getAge()));
        lblValueEmail.setText(patient.getPatientEmail());
        lblValueGender.setText(patient.getPatientSex());
        NotesTextArea.setText(patient.getPhysicianNotes());
    }

    public void populateOrders() {
        DefaultTableModel dtm = (DefaultTableModel) OrderJTable.getModel();
        dtm.setRowCount(0);
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        df.setLenient(false);

        for (Order o : patient.getOrderList().getOrderList()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = o;
            row[1] = o.getDrugObject().getDrugId();
            row[2] = o.getDrugObject().getStrength() + o.getDrugObject().getStrengthUnit() + " / "
                    + o.getDrugObject().getVolume() + o.getDrugObject().getVolumeUnit() + " - "
                    + o.getDrugObject().getDispenseQty() + " " + o.getDrugObject().getDispenseQtyUnit();
            row[3] = df.format(o.getStartDate());
            row[4] = df.format(o.getEndDate());
            row[5] = o.getDrugDose();
            row[6] = (o.getDrugDose() * o.getDrugObject().getDispenseQty()) + " " + o.getDrugObject().getDispenseQtyUnit();
            row[7] = timeStampTemp.format(o.getOrderTimeStamp());
            dtm.addRow(row);
        }
    }

    public void populateLabOrders() {
        DefaultTableModel dtm = (DefaultTableModel) LabOrdersJTable.getModel();
        dtm.setRowCount(0);
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        df.setLenient(false);

        for (LabOrder lo : patient.getLabOrderList().getLabOrderList()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = lo;
            row[1] = lo.getLabId();
            row[2] = df.format(lo.getDateOrdered());
            if (lo.getDateTaken() != null) {
                row[3] = df.format(lo.getDateTaken());
            } else {
                row[3] = " - ";
            }
            row[4] = lo.getResult();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientPanel = new javax.swing.JPanel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientMRN1 = new javax.swing.JLabel();
        lblValuePatientName = new javax.swing.JLabel();
        lblValuePatientMRN = new javax.swing.JLabel();
        PlaceOrderPanel = new javax.swing.JPanel();
        btnPlaceLabOrder = new javax.swing.JButton();
        btnPlaceLabOrder1 = new javax.swing.JButton();
        OrderDetailPanel = new javax.swing.JPanel();
        CreateTabbedPanel = new javax.swing.JTabbedPane();
        OrdersJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderJTable = new javax.swing.JTable();
        LabOrdersJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LabOrdersJTable = new javax.swing.JTable();
        DemographicsPanel = new javax.swing.JPanel();
        lblValueAge = new javax.swing.JLabel();
        lblValueEmail = new javax.swing.JLabel();
        lblValueGender = new javax.swing.JLabel();
        lblValueLocation = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NotesTextArea = new javax.swing.JTextArea();
        btnResetPhysicianNotes = new javax.swing.JButton();
        btnSavePhysicianNotes1 = new javax.swing.JButton();

        PatientPanel.setBackground(new java.awt.Color(204, 204, 255));

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(51, 51, 255));
        lblPatientName.setText("Patient Name:");

        lblPatientMRN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPatientMRN1.setForeground(new java.awt.Color(51, 51, 255));
        lblPatientMRN1.setText("Patient MRN:");

        lblValuePatientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValuePatientName.setForeground(new java.awt.Color(51, 51, 255));
        lblValuePatientName.setText("lbl patient name value");

        lblValuePatientMRN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValuePatientMRN.setForeground(new java.awt.Color(51, 51, 255));
        lblValuePatientMRN.setText("lbl patient mrn value");

        javax.swing.GroupLayout PatientPanelLayout = new javax.swing.GroupLayout(PatientPanel);
        PatientPanel.setLayout(PatientPanelLayout);
        PatientPanelLayout.setHorizontalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatientName)
                    .addComponent(lblPatientMRN1)
                    .addComponent(lblValuePatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValuePatientMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PatientPanelLayout.setVerticalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPatientName)
                .addGap(7, 7, 7)
                .addComponent(lblValuePatientName)
                .addGap(18, 18, 18)
                .addComponent(lblPatientMRN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValuePatientMRN)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PlaceOrderPanel.setBackground(new java.awt.Color(163, 163, 177));

        btnPlaceLabOrder.setBackground(new java.awt.Color(204, 204, 204));
        btnPlaceLabOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceLabOrder.setText("Place Lab Order");
        btnPlaceLabOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceLabOrderActionPerformed(evt);
            }
        });

        btnPlaceLabOrder1.setBackground(new java.awt.Color(204, 204, 204));
        btnPlaceLabOrder1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceLabOrder1.setText("Place Order");
        btnPlaceLabOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceLabOrder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlaceOrderPanelLayout = new javax.swing.GroupLayout(PlaceOrderPanel);
        PlaceOrderPanel.setLayout(PlaceOrderPanelLayout);
        PlaceOrderPanelLayout.setHorizontalGroup(
            PlaceOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlaceOrderPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnPlaceLabOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnPlaceLabOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PlaceOrderPanelLayout.setVerticalGroup(
            PlaceOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlaceOrderPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(PlaceOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceLabOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlaceLabOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        OrderDetailPanel.setBackground(new java.awt.Color(223, 223, 226));

        CreateTabbedPanel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        CreateTabbedPanel.setMinimumSize(new java.awt.Dimension(1100, 1000));
        CreateTabbedPanel.setPreferredSize(new java.awt.Dimension(1400, 1000));

        OrdersJPanel.setMinimumSize(new java.awt.Dimension(1100, 1000));
        OrdersJPanel.setPreferredSize(new java.awt.Dimension(1400, 1000));

        OrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Drug ID", "Drug Composition", "Start Date", "End Date", "Doses", "Dose Quantity", "TimeStamp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(OrderJTable);

        javax.swing.GroupLayout OrdersJPanelLayout = new javax.swing.GroupLayout(OrdersJPanel);
        OrdersJPanel.setLayout(OrdersJPanelLayout);
        OrdersJPanelLayout.setHorizontalGroup(
            OrdersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersJPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        OrdersJPanelLayout.setVerticalGroup(
            OrdersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        CreateTabbedPanel.addTab("Orders", OrdersJPanel);

        LabOrdersJPanel.setMinimumSize(new java.awt.Dimension(1100, 1000));
        LabOrdersJPanel.setPreferredSize(new java.awt.Dimension(1400, 1000));

        LabOrdersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lab Name", "Lab ID", "Date Ordered", "Date of Result", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LabOrdersJTable);

        javax.swing.GroupLayout LabOrdersJPanelLayout = new javax.swing.GroupLayout(LabOrdersJPanel);
        LabOrdersJPanel.setLayout(LabOrdersJPanelLayout);
        LabOrdersJPanelLayout.setHorizontalGroup(
            LabOrdersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabOrdersJPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        LabOrdersJPanelLayout.setVerticalGroup(
            LabOrdersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabOrdersJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        CreateTabbedPanel.addTab("Lab Orders", LabOrdersJPanel);

        javax.swing.GroupLayout OrderDetailPanelLayout = new javax.swing.GroupLayout(OrderDetailPanel);
        OrderDetailPanel.setLayout(OrderDetailPanelLayout);
        OrderDetailPanelLayout.setHorizontalGroup(
            OrderDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        OrderDetailPanelLayout.setVerticalGroup(
            OrderDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        DemographicsPanel.setBackground(new java.awt.Color(163, 163, 177));
        DemographicsPanel.setLayout(null);

        lblValueAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValueAge.setText("lbl age value");
        DemographicsPanel.add(lblValueAge);
        lblValueAge.setBounds(20, 160, 240, 17);

        lblValueEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValueEmail.setText("lbl email value");
        DemographicsPanel.add(lblValueEmail);
        lblValueEmail.setBounds(20, 210, 240, 30);

        lblValueGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValueGender.setText("lbl gender value");
        DemographicsPanel.add(lblValueGender);
        lblValueGender.setBounds(20, 110, 250, 17);

        lblValueLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValueLocation.setText("lbl location value");
        DemographicsPanel.add(lblValueLocation);
        lblValueLocation.setBounds(20, 50, 250, 30);

        backjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton.setText("<< Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        DemographicsPanel.add(backjButton);
        backjButton.setBounds(50, 780, 180, 50);

        lblLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLocation.setText("Location:");
        DemographicsPanel.add(lblLocation);
        lblLocation.setBounds(20, 30, 90, 30);

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGender.setText("Gender:");
        DemographicsPanel.add(lblGender);
        lblGender.setBounds(20, 90, 91, 17);

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAge.setText("Age:");
        DemographicsPanel.add(lblAge);
        lblAge.setBounds(20, 140, 91, 17);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email:");
        DemographicsPanel.add(lblEmail);
        lblEmail.setBounds(20, 187, 36, 30);

        lblNotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNotes.setText("Physician Notes:");
        DemographicsPanel.add(lblNotes);
        lblNotes.setBounds(20, 250, 160, 30);

        NotesTextArea.setColumns(20);
        NotesTextArea.setRows(5);
        jScrollPane3.setViewportView(NotesTextArea);

        DemographicsPanel.add(jScrollPane3);
        jScrollPane3.setBounds(20, 290, 250, 270);

        btnResetPhysicianNotes.setText("Reset Notes");
        btnResetPhysicianNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPhysicianNotesActionPerformed(evt);
            }
        });
        DemographicsPanel.add(btnResetPhysicianNotes);
        btnResetPhysicianNotes.setBounds(30, 580, 100, 29);

        btnSavePhysicianNotes1.setText("Save Notes");
        btnSavePhysicianNotes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePhysicianNotes1ActionPerformed(evt);
            }
        });
        DemographicsPanel.add(btnSavePhysicianNotes1);
        btnSavePhysicianNotes1.setBounds(160, 580, 100, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DemographicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlaceOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlaceOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OrderDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DemographicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceLabOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceLabOrder1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("PlaceOrderPanel", new PlaceOrderPanel(userProcessContainer, userAccount, doctorOrganization, enterprise, patient, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPlaceLabOrder1ActionPerformed

    private void btnPlaceLabOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceLabOrderActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterprise, doctorOrganization, patient, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPlaceLabOrderActionPerformed

    private void btnResetPhysicianNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPhysicianNotesActionPerformed
        // TODO add your handling code here:
        NotesTextArea.setText(PhysicianNotes);
        patient.setPhysicianNotes(NotesTextArea.getText().trim());
    }//GEN-LAST:event_btnResetPhysicianNotesActionPerformed

    private void btnSavePhysicianNotes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePhysicianNotes1ActionPerformed
        // TODO add your handling code here:
        if (!NotesTextArea.getText().trim().isEmpty()) {
            patient.setPhysicianNotes(NotesTextArea.getText().trim());
        }
    }//GEN-LAST:event_btnSavePhysicianNotes1ActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CreateTabbedPanel;
    private javax.swing.JPanel DemographicsPanel;
    private javax.swing.JPanel LabOrdersJPanel;
    private javax.swing.JTable LabOrdersJTable;
    private javax.swing.JTextArea NotesTextArea;
    private javax.swing.JPanel OrderDetailPanel;
    private javax.swing.JTable OrderJTable;
    private javax.swing.JPanel OrdersJPanel;
    private javax.swing.JPanel PatientPanel;
    private javax.swing.JPanel PlaceOrderPanel;
    private javax.swing.JButton backjButton;
    private javax.swing.JButton btnPlaceLabOrder;
    private javax.swing.JButton btnPlaceLabOrder1;
    private javax.swing.JButton btnResetPhysicianNotes;
    private javax.swing.JButton btnSavePhysicianNotes1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPatientMRN1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblValueAge;
    private javax.swing.JLabel lblValueEmail;
    private javax.swing.JLabel lblValueGender;
    private javax.swing.JLabel lblValueLocation;
    private javax.swing.JLabel lblValuePatientMRN;
    private javax.swing.JLabel lblValuePatientName;
    // End of variables declaration//GEN-END:variables
}
