/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Order.*;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Patient patient;
    private DoctorOrganization doctorOrganization;
    private EcoSystem system;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, DoctorOrganization doctorOrganization, Patient patient, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patient = patient;
        this.system = system;
        this.doctorOrganization = doctorOrganization;
        valueLabel.setText(enterprise.getName());
        valuePatientLabel.setText(patient.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearchLab = new javax.swing.JTextField();
        btnSearchLab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LabSearchJTable = new javax.swing.JTable();
        lblPatient = new javax.swing.JLabel();
        valuePatientLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 30));

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearch.setText("Search Lab:");
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtSearchLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchLabActionPerformed(evt);
            }
        });
        add(txtSearchLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 170, 30));

        btnSearchLab.setText("Search");
        btnSearchLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLabActionPerformed(evt);
            }
        });
        add(btnSearchLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        LabSearchJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Time Taken", "Instrument Used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LabSearchJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 420, 120));

        lblPatient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPatient.setText("Patient:");
        add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 30));

        valuePatientLabel.setText("<value>");
        add(valuePatientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        int selectedRow = LabSearchJTable.getSelectedRow();
        if (selectedRow >= 0) {
            Lab lab = (Lab) LabSearchJTable.getValueAt(selectedRow, 0);

            LabOrder newLabOrder = patient.getLabOrderList().addLabOrder();
            newLabOrder.setLabObject(lab);
            newLabOrder.setLabId((int) (Math.random() * 50 + 1));
            newLabOrder.setDateOrdered(new Date());

            String message = lab.getLabTestName();

            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setPatient(patient);
            request.setLabID(newLabOrder.getLabId());

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof LabOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            JOptionPane.showMessageDialog(null, "Lab Request successfully placed");
        } else {
            JOptionPane.showMessageDialog(null, "Please select lab test");
            return;
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientDetailsJPanel pdjp = (PatientDetailsJPanel) component;
        pdjp.populateLabOrders();
        pdjp.populateOrders();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtSearchLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchLabActionPerformed

    private void btnSearchLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLabActionPerformed
        // TODO add your handling code here:
        String searchtext = txtSearchLab.getText().trim().toLowerCase();
        if (searchtext.length() > 0) {
            populateLab();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter search text");
            return;
        }
    }//GEN-LAST:event_btnSearchLabActionPerformed

    public void populateLab() {
        DefaultTableModel dtm = (DefaultTableModel) LabSearchJTable.getModel();
        dtm.setRowCount(0);
        String searchtext = txtSearchLab.getText().trim().toLowerCase();

        for (Lab l : system.getLabListDirectory().getLabList()) {
            if (l.getLabTestName().trim().toLowerCase().contains(searchtext)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = l;
                row[1] = l.getTimeTaken();
                row[2] = l.getInstrument();
                dtm.addRow(row);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LabSearchJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSearchLab;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtSearchLab;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valuePatientLabel;
    // End of variables declaration//GEN-END:variables
}
