/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.Drug;
import Business.Order.Lab;
import Business.Organization.DoctorOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keshav
 */
public class SelectDrugLab extends javax.swing.JPanel {

    /**
     * Creates new form SelectDrugLab
     */
    private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    
    public SelectDrugLab(JPanel userProcessContainer, DoctorOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.doctorOrganization = organization;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        
        rbDrug.setSelected(true);
        changeEnabledtoDrug(true);
    }

    public void changeEnabledtoDrug(boolean isDrug) {

        txtSearchDrug.setEnabled(isDrug);
        btnSearchDrug.setEnabled(isDrug);
        ProductSearchJTable.setEnabled(isDrug);

        txtSearchLab.setEnabled(!isDrug);
        btnSearchLab.setEnabled(!isDrug);
        LabSearchJTable.setEnabled(!isDrug);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbDrug = new javax.swing.JRadioButton();
        rbLab = new javax.swing.JRadioButton();
        lblSearch = new javax.swing.JLabel();
        btnSearchLab = new javax.swing.JButton();
        txtSearchLab = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        LabSearchJTable = new javax.swing.JTable();
        lblSearch1 = new javax.swing.JLabel();
        btnSearchDrug = new javax.swing.JButton();
        txtSearchDrug = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductSearchJTable = new javax.swing.JTable();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        rbDrug.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbDrug.setText("Drug");
        rbDrug.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbDrugItemStateChanged(evt);
            }
        });

        rbLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbLab.setText("Lab");
        rbLab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLabItemStateChanged(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearch.setText("Search Lab:");

        btnSearchLab.setText("Search");
        btnSearchLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLabActionPerformed(evt);
            }
        });

        txtSearchLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchLabActionPerformed(evt);
            }
        });

        LabSearchJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Time Taken", "Instrument Used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LabSearchJTable);

        lblSearch1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearch1.setText("Search Drug:");

        btnSearchDrug.setText("Search");
        btnSearchDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDrugActionPerformed(evt);
            }
        });

        txtSearchDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDrugActionPerformed(evt);
            }
        });

        ProductSearchJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Strength", "Volume", "Dispensse Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ProductSearchJTable);

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(rbDrug)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbLab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnSearchDrug))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchLab, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnSearchLab)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDrug)
                    .addComponent(rbLab))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSearch1)
                        .addComponent(btnSearchDrug))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchLab)
                            .addComponent(lblSearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchLab)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLabActionPerformed
        // TODO add your handling code here:
        String searchtext = txtSearchLab.getText().trim().toLowerCase();
        if (searchtext.length() > 0) {
            populateLab();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter search text");
            return;
        }
    }//GEN-LAST:event_btnSearchLabActionPerformed

    public void populateLab() {
        DefaultTableModel dtm = (DefaultTableModel) LabSearchJTable.getModel();
        dtm.setRowCount(0);
        String searchtext = txtSearchLab.getText().trim().toLowerCase();

        for (Lab l : system.getLabListDirectory().getLabList()) {
            if (l.getLabTestName().trim().toLowerCase().contains(searchtext)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = l;
                row[1] = l.getTimeTaken();
                row[2] = l.getInstrument();
                dtm.addRow(row);
            }

        }
    }
    private void txtSearchLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchLabActionPerformed

    private void btnSearchDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDrugActionPerformed
        // TODO add your handling code here:
        String searchtext = txtSearchDrug.getText().trim().toLowerCase();
        if (searchtext.length() > 0) {
            populateDrug();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter search text");
            return;
        }
    }//GEN-LAST:event_btnSearchDrugActionPerformed

    public void populateDrug() {
        DefaultTableModel dtm = (DefaultTableModel) ProductSearchJTable.getModel();
        dtm.setRowCount(0);
        String searchtext = txtSearchDrug.getText().trim().toLowerCase();

        for (Drug d : system.getDrugListObject().getDrugList()) {
            if (d.getDrugName().trim().toLowerCase().contains(searchtext)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = d;
                row[1] = d.getStrength() + " " + d.getStrengthUnit();
                row[2] = d.getVolume() + " " + d.getVolumeUnit();
                row[3] = d.getDispenseQty() + " " + d.getDispenseQtyUnit();
                dtm.addRow(row);
            }
        }
    }
    private void txtSearchDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDrugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDrugActionPerformed

    private void rbDrugItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbDrugItemStateChanged
        // TODO add your handling code here:
        if (rbDrug.isSelected()) {
            rbLab.setSelected(false);
            DefaultTableModel dtm = (DefaultTableModel) LabSearchJTable.getModel();
            dtm.setRowCount(0);
            txtSearchLab.setText("");
            changeEnabledtoDrug(true);
        }
    }//GEN-LAST:event_rbDrugItemStateChanged

    private void rbLabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLabItemStateChanged
        // TODO add your handling code here:\        
        if (rbLab.isSelected()) {
            rbDrug.setSelected(false);
            DefaultTableModel dtm = (DefaultTableModel) ProductSearchJTable.getModel();
            dtm.setRowCount(0);
            txtSearchDrug.setText("");
            changeEnabledtoDrug(false);
        }
    }//GEN-LAST:event_rbLabItemStateChanged

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        int selectedRow;
        Drug drug = null;
        Lab lab = null;
        if (rbDrug.isSelected()) {
            selectedRow = ProductSearchJTable.getSelectedRow();
            if (selectedRow >= 0) {
                drug = (Drug) ProductSearchJTable.getValueAt(selectedRow, 0);
            } else {
                JOptionPane.showMessageDialog(null, "Please select drug.");
                return;
            }
        } else {
            selectedRow = LabSearchJTable.getSelectedRow();
            if (selectedRow >= 0) {
                lab = (Lab) LabSearchJTable.getValueAt(selectedRow, 0);
            } else {
                JOptionPane.showMessageDialog(null, "Please select lab.");
                return;
            }
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddEditHighRiskCategoriesJPanel", new AddHighRiskCategoriesJPanel(userProcessContainer, doctorOrganization, enterprise, drug, lab));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LabSearchJTable;
    private javax.swing.JTable ProductSearchJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearchDrug;
    private javax.swing.JButton btnSearchLab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearch1;
    private javax.swing.JRadioButton rbDrug;
    private javax.swing.JRadioButton rbLab;
    private javax.swing.JTextField txtSearchDrug;
    private javax.swing.JTextField txtSearchLab;
    // End of variables declaration//GEN-END:variables
}
